version: 2.0

jobs:
    build:
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/agrimont.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "76:22:40:4e:60:92:1b:67:06:1b:16:8a:a3:72:c8:c2"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: | 
                    git clone -b master git@github.com:agrimont/agrimont.github.io.git public
            - run:
                name: Generate site
                working_directory: ~/agrimont.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - run:
                name: Delete All SSH keys and Add the installed one
                command: ssh-add -D && ssh-add ~/.ssh/id_rsa_7622404e60921b67061b168aa372c8c2
            - deploy:
                name: Deploy to Github Pages & FTP
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "k@b-coding.de"
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "Trigger deployment"
                    git push -q git@github.com:agrimont/agrimont.github.io.git master
                    ls -al
                    apk add lftp
                    echo $USER
                    lftp ftp://$USER:$PASS@agrimont.de -e "set ssl:verify-certificate false; mirror -v -R -n --exclude .git/ --exclude .circleci/ --ignore-time --parallel=40 ./ agrimont2019; quit"
    ftp:
        machine:
            image: circleci/classic:latest
        steps:
        - run:
            name: Install LFTP
            command: |
                sudo apt-get update;
                sudo apt-get install lftp;
        - checkout
        - run:
            name: Send Via SFTP
            command: lftp sftp://${username}:${password}@agrimont.de -e "mirror -v -R --exclude .git/ --exclude .circleci/ ./ testtrans; quit"

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: source
